import 'package:flutter/material.dart';
import '2.1.jisuanqi.dart';
import '2.2.newRoutejisuanqi.dart';
import '2.4.images.dart';
import 'selectArea.dart';
import '2.6.debugerlog.dart';
import '3.1.Widget.dart';
import '3.2.stateManager.dart';
import '3.3.Text.dart';
import '3.4.Button.dart';
import '3.5.Image.dart';
import '3.6.SwitchBox.dart';
import '3.7.TextField.dart';
import '3.8.progress.dart';
import '4.1.Widget.dart';
import '4.2.RowColumn.dart';
import '4.3.Flex.dart';
import '4.4.liushibuju.dart';
import '4.5.StackPosition.dart';
import '4.6.StackAlign.dart';
import '5.1.Padding.dart';
import '5.2.Rongqi.dart';
import '5.4.Transform.dart';
import '5.5Container.dart';
import '5.6.Scanffold.TabBar.Navigation.dart';
import '5.7.Clip.dart';
import '6.2SingleChildScrollView.dart';
import '6.3.ListView.dart';
import '6.4.GridView.dart';
import '6.5.CustomScrollView.dart';

import 'isolatedemo.dart';
import 'listView.dart';
import 'textField1.dart';

// void main() => runApp(new JisauanqiMyApp());
//void main() => runApp(new NewRoutejisuanqiMyApp());
// void main() => runApp(new AssetImageApp());
//void main() => runApp(new SelectAreaApp());
//void main() => runApp(new DebugerLogApp());
//void main() => runApp(new Wdg());
//void main() => runApp(new StateManager());
//void main() => runApp(new SampleApp());
//void main() => runApp(new ListViewApp());
//void main() => runApp(new TextFieldApp());
//void main() => runApp(new TextApp());
//void main() =>  runApp(ButtonApp());
//void main() => runApp(ImageApp());
//void main() => runApp(SwitchCheckBoxApp());
//void main() => runApp(TextFieldApp1());
//void main() => runApp(new ProgressApp());
//void main() => runApp(new RowColumnApp());
//void main() => runApp(new FlexApp());
//void main() => runApp(new Liushibuju());
//void main() => runApp(new StackPositionApp());
//void main() => runApp(new StackAlignApp());
//void main() => runApp(new PaddingApp());
//void main() => runApp(new BoxApp());
//void main() => runApp(new TransformApp());
//void main() => runApp(new ContainerApp());
//void main() => runApp(new TabBarNavgationApp());
//void main() => runApp(new ClipApp());
//void main() => runApp(new SingleChildSCrollApp());
//void main() => runApp(new ListViewApp1());
//void main() => runApp(new GridViewApp());
void main() => runApp(new CustomScrollApp());

